// SPDX-License-Identifier: AGPL-3.0-only
// Generated by scripts/gen-locales.mjs from messages/*.json. Do not edit.
export const LOCALES = ['en', 'de', 'es', 'fr', 'it', 'nl'] as const;
export const DEFAULT_LOCALE = 'en';
