#!/usr/bin/env bash
# Refresh the list of Cloudflare addresses the origin trusts - nginx variant.
#
# The Caddy sibling of this script is deploy/web/cloudflare-ips.sh. Use this one
# when the TLS terminator is nginx (deploy/web/velorki.nginx.conf,
# docs/DEPLOY_WEB.md step 4b).
#
# Cloudflare publishes its ranges at https://www.cloudflare.com/ips-v4 and
# ips-v6 (plain text, one CIDR per line) and changes them occasionally. This
# script turns that list into
#
#   /etc/nginx/conf.d/cloudflare-real-ip.conf
#
# holding one `set_real_ip_from <cidr>;` per range plus
# `real_ip_header CF-Connecting-IP;` and `real_ip_recursive on;`, so
# $remote_addr - and therefore the access log and everything nginx forwards - is
# the real visitor rather than a Cloudflare edge node, and only when the
# connection really came from Cloudflare.
#
# Debian/Ubuntu's /etc/nginx/nginx.conf globs conf.d/*.conf into the http block,
# so the file takes effect everywhere on the box; velorki.nginx.conf also
# includes it per server block, which is a harmless re-declaration.
#
# UNLIKE THE CADDY VARIANT, THIS SCRIPT DOES NOT TOUCH ufw. A box running nginx
# is a box that already serves something else, and its firewall is shared: an
# `ufw allow`/`ufw delete` pass owned by Velorki would fight whatever rules the
# other site needs. The commands it *would* run are printed instead - read them,
# decide, apply them by hand if the ranges are all that may reach 443.
#
# Idempotent: it writes and reloads only when the list actually changed, so it
# is safe as a daily cron job.
#
#   sudo install -m 0755 cloudflare-ips-nginx.sh \
#     /usr/local/bin/velorki-cloudflare-ips-nginx
#   sudo velorki-cloudflare-ips-nginx          # BEFORE enabling the site:
#                                              # velorki.nginx.conf includes the
#                                              # file this writes, so `nginx -t`
#                                              # fails while it is missing
#   printf '%s\n' '17 4 * * * root /usr/local/bin/velorki-cloudflare-ips-nginx >>/var/log/velorki-cloudflare-ips.log 2>&1' \
#     | sudo tee /etc/cron.d/velorki-cloudflare-ips
#
# Needs nginx built with the realip module (every distro package is):
#   nginx -V 2>&1 | tr ' ' '\n' | grep realip
set -euo pipefail

SNIPPET=${SNIPPET:-/etc/nginx/conf.d/cloudflare-real-ip.conf}
V4_URL=${V4_URL:-https://www.cloudflare.com/ips-v4}
V6_URL=${V6_URL:-https://www.cloudflare.com/ips-v6}

log() { printf '%s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
die() { log "ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run as root"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# --- fetch -----------------------------------------------------------------
# Both lists or neither: a half-fetched list would make half of Cloudflare's
# traffic look like it came from an untrusted address, so every rate limit for
# those visitors would key on the edge node instead of the rider.
curl -fsS --max-time 20 --retry 3 --retry-delay 2 "$V4_URL" -o "$tmp/v4" \
  || die "cannot fetch $V4_URL"
curl -fsS --max-time 20 --retry 3 --retry-delay 2 "$V6_URL" -o "$tmp/v6" \
  || die "cannot fetch $V6_URL"

# Keep only things that look like CIDRs, so an error page can never become a
# trusted-proxy entry.
grep -Eh '^[0-9a-fA-F:.]+/[0-9]{1,3}$' "$tmp/v4" "$tmp/v6" | sort -u > "$tmp/cidrs"
count=$(wc -l < "$tmp/cidrs")
# Cloudflare publishes ~15 IPv4 and ~7 IPv6 ranges. Far fewer means something
# is wrong with the fetch; refuse rather than shrink the list.
[ "$count" -ge 15 ] || die "only $count ranges parsed, refusing to apply"

# --- nginx snippet ---------------------------------------------------------
{
  echo "# Generated by velorki-cloudflare-ips-nginx on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit."
  echo "# Source: $V4_URL, $V6_URL"
  while read -r cidr; do printf 'set_real_ip_from %s;\n' "$cidr"; done < "$tmp/cidrs"
  # Cloudflare overwrites CF-Connecting-IP at the edge, so it is the one header
  # a client cannot forge - X-Forwarded-For is appended to, not replaced.
  echo 'real_ip_header CF-Connecting-IP;'
  # Single-valued header, so recursion never actually walks a chain; set for
  # the case where real_ip_header is changed to X-Forwarded-For by hand.
  echo 'real_ip_recursive on;'
} > "$tmp/snippet"

changed=0
if ! [ -f "$SNIPPET" ] \
  || ! diff -q <(grep -v '^#' "$SNIPPET") <(grep -v '^#' "$tmp/snippet") >/dev/null 2>&1; then
  # Keep the old file so a failed `nginx -t` can be undone: this box serves
  # another site, and a broken include would take that down too.
  backup=""
  if [ -f "$SNIPPET" ]; then
    backup="$tmp/previous"
    cp -p "$SNIPPET" "$backup"
  fi
  install -m 0644 "$tmp/snippet" "$SNIPPET"
  changed=1
  log "wrote $SNIPPET ($count ranges)"

  if command -v nginx >/dev/null 2>&1; then
    if ! nginx -t >/dev/null 2>&1; then
      if [ -n "$backup" ]; then
        install -m 0644 "$backup" "$SNIPPET"
        log "restored the previous $SNIPPET"
      else
        rm -f "$SNIPPET"
        log "removed $SNIPPET"
      fi
      # Show the operator what nginx objected to.
      nginx -t || true
      die "nginx -t failed, config NOT reloaded"
    fi
  fi
else
  log "$SNIPPET already current ($count ranges)"
fi

# --- firewall: printed, not applied ---------------------------------------
# Deliberately not automated; see the header. Only 443 is listed: 80 is a
# convenience redirect and Cloudflare is told to always use HTTPS.
if [ "$changed" -eq 1 ]; then
  log "firewall NOT changed by this script. To restrict 443 to Cloudflare only:"
  while read -r cidr; do
    printf "  ufw allow from %s to any port 443 proto tcp comment 'cloudflare'\n" "$cidr"
  done < "$tmp/cidrs"
  log "and, once those are in place and verified, remove any blanket rule:"
  printf '  ufw status numbered      # find the number of the open 443/80 rule\n'
  printf '  ufw delete <n>\n'
  log "check what the other site on this box needs first - the firewall is shared."
fi

# --- reload ----------------------------------------------------------------
if [ "$changed" -eq 1 ] && command -v nginx >/dev/null 2>&1; then
  # `reload` and not `restart`: the other site on this box keeps serving.
  systemctl reload nginx && log "nginx reloaded"
fi

log "done"
