#!/usr/bin/env bash
# Refresh the list of Cloudflare addresses the origin trusts and accepts.
#
# Cloudflare publishes its ranges at https://www.cloudflare.com/ips-v4 and
# ips-v6 (plain text, one CIDR per line) and changes them occasionally. This
# script turns that list into
#
#   1. /etc/caddy/cloudflare-ips.caddy   - a `trusted_proxies static ...` line
#                                          imported by /etc/caddy/Caddyfile, so
#                                          CF-Connecting-IP is only believed
#                                          from Cloudflare;
#   2. ufw rules                         - 443/tcp allowed from those ranges and
#                                          from nowhere else, so the header
#                                          cannot be forged by reaching the
#                                          origin directly.
#
# Idempotent: it writes and reloads only when the list actually changed, so it
# is safe as a daily cron job. Run it once by hand before the first Caddy start.
#
#   sudo install -m 0755 cloudflare-ips.sh /usr/local/bin/velorki-cloudflare-ips
#   sudo velorki-cloudflare-ips
#   printf '%s\n' '17 4 * * * root /usr/local/bin/velorki-cloudflare-ips >>/var/log/velorki-cloudflare-ips.log 2>&1' \
#     | sudo tee /etc/cron.d/velorki-cloudflare-ips
set -euo pipefail

SNIPPET=${SNIPPET:-/etc/caddy/cloudflare-ips.caddy}
UFW_COMMENT=${UFW_COMMENT:-cloudflare}
V4_URL=${V4_URL:-https://www.cloudflare.com/ips-v4}
V6_URL=${V6_URL:-https://www.cloudflare.com/ips-v6}

log() { printf '%s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
die() { log "ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run as root"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# --- fetch -----------------------------------------------------------------
# Both lists or neither: a half-fetched list would lock out half of Cloudflare.
curl -fsS --max-time 20 --retry 3 --retry-delay 2 "$V4_URL" -o "$tmp/v4" \
  || die "cannot fetch $V4_URL"
curl -fsS --max-time 20 --retry 3 --retry-delay 2 "$V6_URL" -o "$tmp/v6" \
  || die "cannot fetch $V6_URL"

# Keep only things that look like CIDRs, so an error page can never become a
# firewall rule.
grep -Eh '^[0-9a-fA-F:.]+/[0-9]{1,3}$' "$tmp/v4" "$tmp/v6" | sort -u > "$tmp/cidrs"
count=$(wc -l < "$tmp/cidrs")
# Cloudflare publishes ~15 IPv4 and ~7 IPv6 ranges. Far fewer means something
# is wrong with the fetch; refuse rather than shrink the allowlist.
[ "$count" -ge 15 ] || die "only $count ranges parsed, refusing to apply"

# --- Caddy snippet ---------------------------------------------------------
{
  echo "# Generated by velorki-cloudflare-ips on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit."
  echo "# Source: $V4_URL, $V6_URL"
  printf 'trusted_proxies static'
  while read -r cidr; do printf ' %s' "$cidr"; done < "$tmp/cidrs"
  printf '\n'
} > "$tmp/snippet"

changed=0
if ! [ -f "$SNIPPET" ] || ! diff -q <(grep -v '^#' "$SNIPPET") <(grep -v '^#' "$tmp/snippet") >/dev/null 2>&1; then
  install -m 0644 "$tmp/snippet" "$SNIPPET"
  changed=1
  log "wrote $SNIPPET ($count ranges)"
else
  log "$SNIPPET already current ($count ranges)"
fi

# --- ufw -------------------------------------------------------------------
# Every rule this script owns carries the comment "cloudflare"; the pass below
# deletes the ones that are no longer published and adds the new ones. Rules
# added by hand (SSH, anything else) have a different comment and are untouched.
if command -v ufw >/dev/null 2>&1; then
  current=$(ufw status numbered 2>/dev/null | grep "# $UFW_COMMENT" || true)

  # Delete stale rules from the bottom up, so the numbering stays valid.
  echo "$current" | grep -oE '^\[[ 0-9]+\].*' | tac | while read -r line; do
    num=$(printf '%s' "$line" | sed -E 's/^\[ *([0-9]+)\].*/\1/')
    cidr=$(printf '%s' "$line" | grep -oE '[0-9a-fA-F:.]+/[0-9]{1,3}' | tail -1)
    if [ -n "$cidr" ] && ! grep -qxF "$cidr" "$tmp/cidrs"; then
      yes | ufw delete "$num" >/dev/null
      log "ufw: removed $cidr"
      changed=1
    fi
  done

  while read -r cidr; do
    if ! printf '%s' "$current" | grep -qF "$cidr"; then
      ufw allow from "$cidr" to any port 443 proto tcp comment "$UFW_COMMENT" >/dev/null
      log "ufw: allowed $cidr → 443/tcp"
      changed=1
    fi
  done < "$tmp/cidrs"
else
  log "ufw not installed, skipping firewall rules"
fi

# --- reload ----------------------------------------------------------------
if [ "$changed" -eq 1 ] && command -v caddy >/dev/null 2>&1; then
  # Validate before reloading: a broken snippet must not take the site down.
  if caddy validate --config /etc/caddy/Caddyfile >/dev/null 2>&1; then
    systemctl reload caddy && log "caddy reloaded"
  else
    die "caddy validate failed, config NOT reloaded"
  fi
fi

log "done"
