// SPDX-License-Identifier: AGPL-3.0-only
// Writes src/i18n/locales.generated.ts from the catalogues in messages/. A
// translation merged from Crowdin (messages/fr.json) enables the locale on the
// next run; routing.ts is imported by client code and cannot read the directory.
import { readdirSync, writeFileSync, readFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const locales = readdirSync(`${root}messages`)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.replace(/\.json$/, ''))
  .sort((a, b) => (a === 'en' ? -1 : b === 'en' ? 1 : a.localeCompare(b)));
if (!locales.includes('en')) throw new Error('messages/en.json is the source catalogue and must exist');
const out = `// SPDX-License-Identifier: AGPL-3.0-only
// Generated by scripts/gen-locales.mjs from messages/*.json. Do not edit.
export const LOCALES = [${locales.map((l) => `'${l}'`).join(', ')}] as const;
export const DEFAULT_LOCALE = 'en';
`;
const target = `${root}src/i18n/locales.generated.ts`;
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== out) {
    console.error('src/i18n/locales.generated.ts is stale; run `npm run locales`');
    process.exit(1);
  }
} else {
  writeFileSync(target, out);
}
console.log(`locales: ${locales.join(', ')}`);
