#!/usr/bin/env bash
# Takes the product screenshots the website shows, on the Android emulator.
#
#   tool/screenshots.sh                 # build, seed, capture the whole matrix
#   tool/screenshots.sh --no-build      # keep the installed app
#   tool/screenshots.sh --no-seed       # keep the demo route, ride and tile
#   tool/screenshots.sh --only dark-volt # one appearance only (repeatable)
#   tool/screenshots.sh --screens planner,settings   # only these screens
#   tool/screenshots.sh --lang de       # the app in German (default: en)
#
# Output: web/public/screenshots/<lang>/<mode>-<accent>/<screen>.png plus
# web/public/screenshots/manifest.json. Screens are planner, loop, search,
# navigation, recording, ride, library, offline and settings; the appearance
# matrix is light-volt, dark-volt, dark-ember, dark-glacier and dark-berry.
# One run takes one language; the manifest lists every language found on disk,
# so a German run leaves the English set alone.
#
# Requirements
# ------------
# * The `velorki` emulator, running and booted (`~/Work/bin/velorki-emu`);
#   the phone is never touched, the serial is fixed to emulator-5554 unless
#   VELORKI_SHOT_DEVICE says otherwise.
# * `mise` (Flutter 3.47 and Java 21), the Android platform tools, python3 and
#   `env/local.json` (git-ignored; it points the tile mirror at 10.0.2.2:8000).
# * Network: the map style and its raster tiles come from OpenFreeMap. Routing,
#   the gazetteer and the loop search all run on the device.
#
# How it works, and why
# ---------------------
# * **The tile mirror** (`tool/itest_mirror.sh`) serves the frozen oracle tile
#   W20_N30 — Madeira — on port 8000, the same one the integration suite uses
#   with VELORKI_ITEST_REGION=madeira. The app downloads it through its own
#   offline screen, so the routing in every shot is the on-device engine.
# * **The debug banner** is patched out of `lib/app/app.dart` for the length of
#   the build and put back immediately afterwards (a debug build is required:
#   `env/local.json` points at a cleartext mirror, which a profile build
#   blocks). The marker line is removed again by `restore_banner`, which also
#   runs from the EXIT trap, so an interrupted run leaves the tree clean.
# * **The demo data** is two GPX files in tool/screenshots/, regenerated by
#   `gen_demo_gpx.py`: a 24.5 km loop around Funchal as a `<trk>` with
#   timestamps (imported as a ride) and the same loop as a `<rte>` (imported as
#   a route). The track is sampled every ten seconds rather than every N
#   metres: the app measures an imported ride exactly like a recorded one, and
#   a gap of over 30 s between two fixes counts as a break that contributes
#   neither distance nor moving time (`lib/core/geo/ride_stats.dart`), so a
#   sparse track loses every slow climb.
# * **Getting a file into the app.** `file:///sdcard/Download/...` does not
#   work on API 33+: the intent reaches the activity, but scoped storage stops
#   the app reading the path, and the URI then falls through to go_router as an
#   unknown deep link ("Page Not Found"). A MediaStore `content://` URI is one
#   way round it; the shorter one, used here, is `adb shell run-as` to copy the
#   file into the app's own files directory and to point the VIEW intent at
#   that path, which the app may read.
# * **The language** is the app's own setting, never the system's: the key
#   `flutter.language.locale` in the same shared_prefs file, holding a language
#   tag. English is the absence of the key — that is what "System" means to
#   `LanguageSetting` — and the key is taken out again at the end of every run,
#   so the emulator is handed back on System. Every label the script waits for
#   or taps is translated too, so the selectors live in one table (`UI`) keyed
#   by language; a name with no entry for the language falls back to English,
#   which is right for the demo route and ride names: proper nouns, seeded
#   once and never re-imported per language.
# * **Appearance** is written straight into `shared_prefs/FlutterSharedPreferences.xml`
#   through `run-as`, with the app force-stopped first — shared_preferences
#   holds the map in memory and would write it back over anything changed
#   underneath it. The same file seeds the map camera, so every shot starts
#   over Funchal instead of wherever the last run left the map.
# * **Typing** happens by tapping the on-screen keyboard, never with
#   `adb shell input text`. A key event puts the window into Android's
#   focus-highlight mode, which then draws an accent-coloured border around the
#   whole window until the app is restarted — and that border lands in every
#   screenshot after it.
# * **The turn banner** needs a routed route: an imported GPX carries no turn
#   instructions, so following it only ever says "Continue". The seed therefore
#   plans Funchal → Monte with the on-device router, saves it, and reads its
#   geometry back out of the app database with `screenshots/unpack_route.py` so
#   `tool/emu_ride.py --path` can ride exactly that line.
#
# The script is idempotent: it skips the seeding steps whose result is already
# in the app database, and re-taking one screen overwrites one file.
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd .. && pwd)"
HERE="$PWD/tool/screenshots"
OUT="${VELORKI_SHOT_OUT:-$ROOT/web/public/screenshots}"
SERIAL="${VELORKI_SHOT_DEVICE:-emulator-5554}"
PKG=com.orkitec.velorki
APP_FILES="/data/user/0/$PKG/files"
WORK="$(mktemp -d)"
export PATH="$HOME/Android/Sdk/platform-tools:$PATH"

ALL_SCREENS=(planner loop search navigation recording ride library offline settings)
ALL_LOOKS=(light-volt dark-volt dark-ember dark-glacier dark-berry)
DO_BUILD=1
DO_SEED=1
LANG_TAG=en
LOOKS=()
SCREENS=()

while [ $# -gt 0 ]; do
  case "$1" in
    --no-build) DO_BUILD=0 ;;
    --no-seed) DO_SEED=0 ;;
    --only) IFS=, read -r -a extra <<< "$2"; LOOKS+=("${extra[@]}"); shift ;;
    --screens) IFS=, read -r -a SCREENS <<< "$2"; shift ;;
    --lang) LANG_TAG="$2"; shift ;;
    -h | --help) sed -n '2,/^set -euo/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//;$d'; exit 0 ;;
    *) printf 'unknown argument %q\n' "$1" >&2; exit 2 ;;
  esac
  shift
done
if [ ${#LOOKS[@]} -eq 0 ]; then LOOKS=("${ALL_LOOKS[@]}"); fi
if [ ${#SCREENS[@]} -eq 0 ]; then SCREENS=("${ALL_SCREENS[@]}"); fi
[[ $LANG_TAG =~ ^[a-z]{2,3}([-_][A-Za-z0-9]+)*$ ]] \
  || { printf 'not a language tag: %q\n' "$LANG_TAG" >&2; exit 2; }

say() { printf '==> %s\n' "$*"; }
die() { printf '::error::%s\n' "$*" >&2; exit 1; }
A() { adb -s "$SERIAL" "$@"; }

# ---------------------------------------------------------------- the device

require_device() {
  command -v adb > /dev/null || die "adb is not on PATH (\$HOME/Android/Sdk/platform-tools)."
  if ! adb devices | grep -q "^$SERIAL[[:space:]]*device$"; then
    die "$SERIAL is not attached. Start it with ~/Work/bin/velorki-emu and wait for sys.boot_completed."
  fi
  [ "$(A shell getprop sys.boot_completed | tr -d '\r')" = 1 ] || die "$SERIAL has not finished booting."
  RES="$(A shell wm size | tr -d '\r' | awk '{print $NF}')"
  [ "$RES" = "1080x2400" ] || say "warning: this screen is $RES; the keyboard and pan offsets are tuned for 1080x2400."
  DENSITY="$(A shell wm density | tr -d '\r' | awk '{print $NF}')"
}

# ---------------------------------------------------------------- the labels
#
# Every label the script waits for or taps, per language, because the app is
# shown in --lang and its own widgets are translated with it. `ui <name>` takes
# the entry for the current language and falls back to the English one, which
# is what the demo route and ride names need: proper nouns, seeded once and
# never re-imported per language.
#
# Upper-case names are the captions `StatTile`, `SectionCaption` and the
# recording pill render with `toUpperCase()`, so they are matched upper-case.
# The German entries come from `lib/l10n/app_de.arb`; `Zurück`, `Schließen`,
# `Menü anzeigen` and `Tab 1 von 4` come from Flutter's own
# `material_de.arb`, which is where those tooltips are translated.
declare -A UI=(
  [en:tabbar]='Tab 1 of 4'
  [de:tabbar]='Tab 1 von 4'
  [en:tab_plan]='Plan'
  [de:tab_plan]='Planen'
  [en:tab_record]='Record'
  [de:tab_record]='Aufnahme'
  [en:tab_library]='Library'
  [de:tab_library]='Bibliothek'
  [en:tab_settings]='Settings'
  [de:tab_settings]='Optionen'
  [en:back]='^Back$'
  [de:back]='^Zurück$'
  [en:dismiss]='^Dismiss$'
  [de:dismiss]='^Schließen$'
  [en:menu]='^Show menu$'
  [de:menu]='^Menü anzeigen$'
  [en:delete]='^Delete$'
  [de:delete]='^Löschen$'
  [en:save]='^Save$'
  [de:save]='^Speichern$'
  [en:import]='^Import$'
  [en:kind_Route]='^Route$'
  [en:kind_Ride]='^Ride$'
  [de:kind_Ride]='^Fahrt$'
  [en:snack]='Undo$|deleted$|added to'
  [de:snack]='Rückgängig$|gelöscht$|hinzugefügt'
  [en:undo]='Undo'
  [de:undo]='Rückgängig'
  [en:empty_plan]='Tap the map to set a start'
  [de:empty_plan]='Karte antippen, um den Start zu setzen'
  [en:DISTANCE]='DISTANCE'
  [de:DISTANCE]='DISTANZ'
  # The map's own controls and the location rationale, from the ARB like
  # everything else since the map strings moved into it.
  [en:locate]='^Show my position$'
  [de:locate]='^Meine Position anzeigen$'
  [en:zoom_out]='^Zoom out$'
  [de:zoom_out]='^Herauszoomen$'
  [en:offline_entry]='^Offline data$'
  [de:offline_entry]='^Offline-Daten$'
  [en:rationale_allow]='^Continue$'
  [de:rationale_allow]='^Weiter$'
  [en:download_visible]='^Download the visible area$'
  [de:download_visible]='^Sichtbares Gebiet herunterladen$'
  [en:download]='^Download$'
  [de:download]='^Herunterladen$'
  [en:routing_data]='Routing data'
  [de:routing_data]='Routing-Daten'
  [en:search_hint]='^Search for a place$'
  [de:search_hint]='^Ort suchen$'
  [en:search_clear]='^Clear search'
  [de:search_clear]='^Suche leeren'
  [en:hit_monte]='Suburb · Funchal'
  [de:hit_monte]='Stadtteil · Funchal'
  [en:hit_funchal]='City$|Locality · Funchal'
  [de:hit_funchal]='Stadt$|Ortslage · Funchal'
  [en:from_position]='^From my position$'
  [de:from_position]='^Von meiner Position$'
  [en:save_route]='^Save route$'
  [de:save_route]='^Route speichern$'
  # plannerDefaultRouteName is "Route {date}" in both languages.
  [en:default_route_name]='Route Sep|Route [A-Z]'
  [en:loop_make]='^Make a loop$'
  [de:loop_make]='^Runde planen$'
  [en:loop_result]='km · .* up|No loop found|Loop search failed'
  [de:loop_result]='km · .* Anstieg|keine Runde gefunden|Rundensuche fehlgeschlagen'
  [en:loop_done]='^Done$'
  [de:loop_done]='^Fertig$'
  [en:follow_route]='^Follow a route'
  [de:follow_route]='^Einer Route folgen'
  [en:no_route]='No route'
  [de:no_route]='Keine Route'
  [en:start_ride]='^Start ride$'
  [de:start_ride]='^Fahrt starten$'
  # Two dialogs say it: the battery one and the location rationale.
  [en:not_now]='^Not now$'
  [de:not_now]='^Jetzt nicht$'
  [en:RECORDING]='RECORDING'
  [de:RECORDING]='AUFNAHME'
  [en:finish]='^Finish$'
  [de:finish]='^Beenden$'
  [en:lib_routes]='^Routes$'
  [de:lib_routes]='^Routen$'
  [en:lib_rides]='^Rides$'
  [de:lib_rides]='^Fahrten$'
  [en:open_in_planner]='^Open in planner'
  [de:open_in_planner]='^Im Planer öffnen'
  [en:SLOW]='SLOW'
  [de:SLOW]='LANGSAM'
  [en:turn]='^(Turn|Bear|Sharp|Keep) '
  [de:turn]='abbieg|halten|^Wenden|Ausfahrt'
  [en:metres]='^[0-9]+ m$'
)

ui() {  # ui <name> -> the selector for --lang, or the English one
  local entry=${UI["$LANG_TAG:$1"]-}
  [ -n "$entry" ] || entry=${UI["en:$1"]-}
  [ -n "$entry" ] || die "no label named $1"
  printf '%s' "$entry"
}

# --------------------------------------------------------------- the ui tree

dump() {
  local try
  for try in 1 2 3; do
    A shell uiautomator dump /sdcard/velorki-ui.xml > /dev/null 2>&1 || true
    if A shell cat /sdcard/velorki-ui.xml > "$WORK/ui.xml" 2> /dev/null \
      && [ -s "$WORK/ui.xml" ]; then
      return 0
    fi
    sleep 1
  done
  return 1
}

# node <regex> [nth] -> "cx cy x1 y1 x2 y2", matched against content-desc, text
# and the hint of every node in a fresh dump.
node() { dump && python3 "$HERE/ui.py" find "$WORK/ui.xml" "$1" "${2:-0}"; }

has() { node "$1" "${2:-0}" > /dev/null 2>&1; }

tap_xy() { A shell input tap "$1" "$2"; }

tap() {  # tap <regex> [nth] [fraction of the node's height, default 50]
  local p fy=${3:-50}
  p=$(node "$1" "${2:-0}") || { printf '::error::no node matching %q\n' "$1" >&2; return 1; }
  # `set --` overwrites the positional parameters, so read $3 before it.
  set -- $p
  tap_xy "$1" "$(( $4 + ($6 - $4) * fy / 100 ))"
}

# Waits until <regex> is on screen. wait_for <regex> [seconds] [message]
wait_for() {
  local pattern=$1 limit=${2:-60} i
  for ((i = 0; i < limit; i++)); do
    has "$pattern" && return 0
    sleep 1
  done
  printf '::error::%s\n' "${3:-timed out waiting for /$pattern/}" >&2
  return 1
}

wait_gone() {
  local pattern=$1 limit=${2:-60} i
  for ((i = 0; i < limit; i++)); do
    has "$pattern" || return 0
    sleep 1
  done
  return 1
}

# A snackbar ("… deleted", "… added to the library") sits over the bottom of
# the screen for a good while and swallows taps meant for the button under it.
# Swiping it out to the left dismisses it.
SNACK="$(ui snack)"

dismiss_snackbar() {
  local i p x y
  for i in 1 2 3 4; do
    p=$(node "$SNACK") || return 0
    # Read the coordinates out before `set --` touches the arguments; the bar
    # floats at a different height on a screen that has a bottom bar of its own.
    x=${p%% *}
    # Drag from the bar's top edge, not its middle: on a screen whose own
    # controls end low the bar sits so far down that a drag from the middle
    # would have to end off the screen, and that swipe is thrown away.
    y=$(printf '%s' "$p" | cut -d' ' -f4)
    y=$(( y + 20 ))
    # Downwards: that is the SnackBar's dismiss direction, and with an
    # accessibility client attached (uiautomator is one) a snackbar never
    # times out on its own, so this is the only way it goes.
    A shell input swipe "$x" "$y" "$x" 2390 250
    sleep 2
    if wait_gone "$SNACK" 12; then return 0; fi
  done
  say "a snackbar will not go away; the next shot may show it"
}

# ------------------------------------------------------------- the keyboard
#
# Gboard's QWERTY centres on a 1080x2400 screen. Tapped, never typed: see the
# header on why a key event would tint the whole window.
declare -A KEYX=(
  [q]=58 [w]=164 [e]=271 [r]=379 [t]=486 [y]=592 [u]=700 [i]=806 [o]=913 [p]=1020
  [a]=112 [s]=218 [d]=325 [f]=432 [g]=539 [h]=646 [j]=752 [k]=859 [l]=966
  [z]=218 [x]=325 [c]=432 [v]=539 [b]=646 [n]=752 [m]=859
)
declare -A KEYY=(
  [q]=1714 [w]=1714 [e]=1714 [r]=1714 [t]=1714 [y]=1714 [u]=1714 [i]=1714 [o]=1714 [p]=1714
  [a]=1870 [s]=1870 [d]=1870 [f]=1870 [g]=1870 [h]=1870 [j]=1870 [k]=1870 [l]=1870
  [z]=2026 [x]=2026 [c]=2026 [v]=2026 [b]=2026 [n]=2026 [m]=2026
)
KEY_SHIFT=(84 2026)
KEY_SPACE=(592 2180)
KEY_BACKSPACE=(993 2026)
KEY_HIDE=(160 2335)

keyboard_up() { [ "$(A shell dumpsys input_method | tr -d '\r' | grep -c 'mInputShown=true')" -gt 0 ]; }

type_text() {  # letters and spaces only; a capital taps shift first
  local s=$1 i c
  for ((i = 0; i < ${#s}; i++)); do
    c=${s:i:1}
    if [ "$c" = " " ]; then
      tap_xy "${KEY_SPACE[@]}"
      sleep 0.3
      continue
    fi
    if [[ $c =~ [A-Z] ]]; then
      tap_xy "${KEY_SHIFT[@]}"
      sleep 0.3
      c=${c,}
    fi
    tap_xy "${KEYX[$c]}" "${KEYY[$c]}"
    sleep 0.35
  done
}

erase() { local n=$1 i; for ((i = 0; i < n; i++)); do tap_xy "${KEY_BACKSPACE[@]}"; sleep 0.2; done; }

hide_keyboard() {
  if keyboard_up; then
    tap_xy "${KEY_HIDE[@]}"
    sleep 2
  fi
}

# ------------------------------------------------------------ shared_prefs

DOUBLE_PREFIX='VGhpcyBpcyB0aGUgcHJlZml4IGZvciBEb3VibGUu'

set_prefs() {  # set_prefs key=value ...  (the app is stopped and left stopped)
  local kv entries=""
  for kv in "$@"; do
    entries+="    <string name=\"flutter.${kv%%=*}\">${kv#*=}</string>"$'\n'
  done
  A shell am force-stop "$PKG"
  sleep 2
  A shell "run-as $PKG sh -c 'cat > shared_prefs/FlutterSharedPreferences.xml'" << XML
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
$entries</map>
XML
}

launch() {
  A shell am force-stop "$PKG"
  sleep 2
  A shell am start -n "$PKG/.MainActivity" > /dev/null
  # The floating tab bar is on every tab, so it says the shell is up whatever
  # the app opens on.
  wait_for "$(ui tabbar)" 90 "the app did not come up"
  sleep 5
}

# The app's own language, patched into the prefs file rather than written over
# it: this runs before the seeding, which taps its way through the very same
# translated labels, and again at the end of a run to hand the emulator back on
# System. English is the absence of the key; `set_prefs` rewrites the whole
# file, so `restart_with` puts the key back for every appearance.
set_language() {  # set_language <tag|en>
  say "app language: ${1/#en/System (English)}"
  A shell am force-stop "$PKG"
  sleep 2
  A shell "run-as $PKG cat shared_prefs/FlutterSharedPreferences.xml" \
    > "$WORK/prefs.xml" 2> /dev/null || : > "$WORK/prefs.xml"
  VELORKI_LANG="$1" python3 - "$WORK/prefs.xml" << 'PY'
import os, re, sys

path, tag = sys.argv[1], os.environ["VELORKI_LANG"]
body = open(path).read()
if "<map" not in body:
    body = ("<?xml version='1.0' encoding='utf-8' standalone='yes' ?>\n"
            "<map>\n</map>\n")
body = body.replace("<map />", "<map>\n</map>").replace("<map/>", "<map>\n</map>")
body = re.sub(r'\s*<string name="flutter\.language\.locale">[^<]*</string>', "", body)
if tag not in ("en", "system"):
    body = body.replace(
        "<map>",
        f'<map>\n    <string name="flutter.language.locale">{tag}</string>', 1)
open(path, "w").write(body)
PY
  A shell "run-as $PKG sh -c 'cat > shared_prefs/FlutterSharedPreferences.xml'" < "$WORK/prefs.xml"
}

restart_with() {  # restart_with <mode> <accent>
  # Android's own theme too, so the on-screen keyboard in the search shot
  # matches the app rather than glaring white over a dark map.
  if [ "$1" = dark ]; then
    A shell cmd uimode night yes > /dev/null
  else
    A shell cmd uimode night no > /dev/null
  fi
  sleep 2
  local prefs=(
    "appearance.mode=$1"
    "appearance.accent=$2"
    "appearance.map=auto"
    "units.system=metric"
    "map.camera.lat=${DOUBLE_PREFIX}32.682"
    "map.camera.lon=${DOUBLE_PREFIX}-16.929"
    "map.camera.zoom=${DOUBLE_PREFIX}11.4"
  )
  # The whole file is rewritten, so the language has to come along; leaving it
  # out is what English (System) is.
  [ "$LANG_TAG" = en ] || prefs+=("language.locale=$LANG_TAG")
  set_prefs "${prefs[@]}"
  launch
}

# ------------------------------------------------------------- the app build

BANNER_MARK='      // VELORKI_SCREENSHOTS: taken out again as soon as the build is done.'

restore_banner() {
  [ -f lib/app/app.dart ] || return 0
  grep -q 'VELORKI_SCREENSHOTS' lib/app/app.dart || return 0
  python3 - << 'PY'
path = "lib/app/app.dart"
mark = "      // VELORKI_SCREENSHOTS: taken out again as soon as the build is done.\n"
flag = "      debugShowCheckedModeBanner: false,\n"
body = open(path).read().replace(mark + flag, "", 1)
open(path, "w").write(body)
PY
}
trap 'restore_banner; rm -rf "$WORK"' EXIT

build_and_install() {
  say "building the debug APK"
  restore_banner
  python3 - << 'PY'
path = "lib/app/app.dart"
mark = "      // VELORKI_SCREENSHOTS: taken out again as soon as the build is done.\n"
flag = "      debugShowCheckedModeBanner: false,\n"
body = open(path).read()
assert "return MaterialApp.router(\n" in body, "lib/app/app.dart no longer starts the app the way this script expects"
open(path, "w").write(body.replace("return MaterialApp.router(\n",
                                   "return MaterialApp.router(\n" + mark + flag, 1))
PY
  local rc=0
  mise exec -- flutter build apk --debug --dart-define-from-file=env/local.json || rc=$?
  restore_banner
  [ "$rc" -eq 0 ] || die "the debug build failed"
  say "installing on $SERIAL"
  A install -r build/app/outputs/flutter-apk/app-debug.apk > /dev/null
  for p in ACCESS_FINE_LOCATION ACCESS_COARSE_LOCATION POST_NOTIFICATIONS; do
    A shell pm grant "$PKG" "android.permission.$p" 2> /dev/null || true
  done
}

start_mirror() {
  if curl -fsS http://127.0.0.1:8000/manifest.json > /dev/null 2>&1; then
    say "the tile mirror is already serving on port 8000"
    return
  fi
  say "starting the tile mirror"
  bash tool/itest_mirror.sh > /dev/null
}

# --------------------------------------------------------------- the seeding

db() {  # db <sql> -> one value per line
  # Drift runs SQLite in WAL mode, so the newest rows are in the -wal file
  # rather than the database: copying only the database reads a state that is
  # a few writes behind, which looks exactly like an import that never
  # happened.
  A shell "run-as $PKG cat app_flutter/velorki.sqlite" > "$WORK/velorki.sqlite" 2> /dev/null || return 1
  A shell "run-as $PKG cat app_flutter/velorki.sqlite-wal" > "$WORK/velorki.sqlite-wal" 2> /dev/null || true
  A shell "run-as $PKG cat app_flutter/velorki.sqlite-shm" > "$WORK/velorki.sqlite-shm" 2> /dev/null || true
  python3 - "$WORK/velorki.sqlite" "$1" << 'PY'
import sqlite3, sys
try:
    for row in sqlite3.connect(sys.argv[1]).execute(sys.argv[2]):
        print("|".join("" if v is None else str(v) for v in row))
except sqlite3.Error:
    pass
PY
}

has_row() { [ -n "$(db "$1" 2> /dev/null)" ]; }

push_gpx() {  # into the app's own files dir, the one place it may read from
  local name=$1
  A push "$HERE/$name" "/sdcard/Download/$name" > /dev/null
  A shell "run-as $PKG sh -c 'cat > files/$name' < /sdcard/Download/$name"
}

import_gpx() {  # import_gpx <file> <Route|Ride> <expected row name>
  local file=$1 kind=$2
  push_gpx "$file"
  # A fresh process: the import preview is reached from the launch intent, and
  # a snackbar left over from an earlier screen would cover the Save button.
  A shell am force-stop "$PKG"
  sleep 3
  A shell am start -a android.intent.action.VIEW \
    -d "file://$APP_FILES/$file" -t application/gpx+xml "$PKG" > /dev/null
  wait_for "$(ui import)" 90 "the import preview did not open for $file"
  wait_for "$(ui save)" 60
  sleep 4
  tap "$(ui "kind_$kind")"
  sleep 2
  dismiss_snackbar
  tap "$(ui save)"
  sleep 10
}

seed_tile() {
  if has_row "select name from routing_tiles where name = 'W20_N30' and state = 'ready'"; then
    say "the W20_N30 routing tile is already on the device"
    return
  fi
  say "downloading the Madeira routing tile and the map area"
  A emu geo fix -16.9075 32.6465 > /dev/null
  sleep 2
  tap "$(ui locate)"
  sleep 8
  tap "$(ui offline_entry)"
  wait_for "$(ui download_visible)" 30
  tap "$(ui download_visible)"
  wait_for "$(ui download)" 30
  tap "$(ui download)"
  for _ in $(seq 1 30); do
    if has_row "select name from routing_tiles where state = 'ready'"; then break; fi
    sleep 5
  done
  has_row "select name from routing_tiles where state = 'ready'" \
    || die "the routing tile did not download; is the mirror on port 8000 up?"
  sleep 10
  tap "$(ui back)" || true
  sleep 3
}

seed_navigation_route() {
  if has_row "select id from routes where name = 'Funchal to Monte'"; then
    say "the navigation route is already saved"
  else
    say "planning Funchal → Monte on the device"
    tap "^$(ui tab_plan)"
    sleep 4
    A emu geo fix -16.9075 32.6465 > /dev/null
    sleep 3
    tap "$(ui search_hint)"
    sleep 4
    type_text "Monte"
    wait_for "$(ui hit_monte)" 30 "the offline gazetteer found no Monte"
    tap "$(ui hit_monte)"
    wait_for "$(ui from_position)" 30
    tap "$(ui from_position)"
    wait_for "$(ui DISTANCE)" 180 "the on-device router did not answer"
    tap "$(ui save)"
    wait_for "$(ui save_route)" 30
    local p
    p=$(node "$(ui default_route_name)")
    set -- $p
    tap_xy "$(( $5 - 30 ))" "$2"
    sleep 2
    erase 26
    sleep 1
    type_text "Funchal to Monte"
    sleep 2
    tap "$(ui save)" 1
    sleep 6
    has_row "select id from routes where name = 'Funchal to Monte'" \
      || die "the planned route was not saved"
  fi
  say "reading its geometry back for tool/emu_ride.py"
  db "select 1" > /dev/null || true
  python3 "$HERE/unpack_route.py" "$WORK/velorki.sqlite" "Funchal to Monte" > "$WORK/monte.path"
  [ "$(wc -l < "$WORK/monte.path")" -gt 20 ] || die "the saved route decoded to almost nothing"
}

seed_extra() {  # seed_extra <table> <name> <file> <Route|Ride>
  if has_row "select id from $1 where name = '$2'"; then
    say "$2 is already in the library"
  else
    import_gpx "$3" "$4"
  fi
}

seed() {
  say "seeding the demo state"
  launch
  seed_tile
  if has_row "select id from routes where name = 'Funchal coast and Monte route'"; then
    say "the demo route is already in the library"
  else
    import_gpx demo-route.gpx Route
  fi
  if has_row "select id from rides where name = 'Funchal coast and Monte loop'"; then
    say "the demo ride is already in the library"
  else
    import_gpx demo-loop.gpx Ride
  fi
  # A few shorter files as well, so the library and the Record tab's recent
  # rides do not read as a fresh install.
  seed_extra routes "Praia Formosa and back" demo-formosa.gpx Route
  seed_extra routes "Monte and the Levada dos Tornos" demo-levada.gpx Route
  seed_extra rides "Evening seafront spin" demo-seafront.gpx Ride
  seed_extra rides "Camara de Lobos climb" demo-camara.gpx Ride
  seed_navigation_route
  # The rider's line for the plain recording shot: the first couple of
  # kilometres of the demo loop, along the Funchal seafront.
  head -14 "$HERE/demo-loop.path" > "$WORK/seafront.path"
}

# ------------------------------------------------------------ the status bar

demo_mode() {
  say "putting the status bar into demo mode"
  A shell settings put global sysui_demo_allowed 1
  local d="am broadcast -a com.android.systemui.demo"
  A shell $d -e command enter > /dev/null
  A shell $d -e command clock -e hhmm 0941 > /dev/null
  A shell $d -e command battery -e level 100 -e plugged false > /dev/null
  A shell $d -e command network -e wifi show -e level 4 -e fully true > /dev/null
  A shell $d -e command network -e mobile hide > /dev/null
  A shell $d -e command notifications -e visible false > /dev/null
  A shell $d -e command status -e volume hide -e bluetooth hide -e location hide \
    -e alarm hide -e sync hide -e tty hide -e eri hide -e mute hide -e speakerphone hide > /dev/null
  sleep 2
}

demo_mode_off() {
  say "leaving demo mode"
  A shell am broadcast -a com.android.systemui.demo -e command exit > /dev/null || true
  # The dark captures put Android itself into night mode; hand the emulator
  # back the way it was found.
  A shell cmd uimode night no > /dev/null || true
}

# -------------------------------------------------------------- the captures

shot() {  # shot <mode-accent> <screen>
  local dir="$OUT/$LANG_TAG/$1"
  mkdir -p "$dir"
  dismiss_snackbar
  sleep 1
  A exec-out screencap -p > "$dir/$2.png"
  local bytes
  bytes=$(stat -c%s "$dir/$2.png")
  [ "$bytes" -gt 20000 ] || die "$dir/$2.png came out empty ($bytes bytes)"
  printf '    %s/%s/%s.png (%s kB)\n' "$LANG_TAG" "$1" "$2" "$(( bytes / 1024 ))"
}

go_tab() {
  # The bar is not drawn while the keyboard is up, and the search field takes
  # the focus back when a pushed screen is popped, so put the keyboard away
  # before looking for a tab.
  hide_keyboard
  # Twice: the first tap switches branch, the second pops that branch back to
  # its root, because a screen pushed inside a tab (a route detail, say) stays
  # on its stack when another tab is shown.
  tap "^$1"
  sleep 2
  tap "^$1"
  sleep 4
}

clear_plan() {  # the action row is one merged semantics node; Clear is 3rd of 5
  local i p x1 y1 x2 y2
  go_tab "$(ui tab_plan)"
  # Up to three goes: the sheet is not always built by the time the tab
  # switch settles, and a ride that was re-routed puts its new line back into
  # the plan, which would otherwise be followed by the next "No route" ride.
  for i in 1 2 3; do
    sleep 3
    # The empty-plan headline. Checking for DISTANCE instead would miss a plan
    # that holds one lone waypoint and no route, which is enough to make the
    # Record tab offer "The route on the Plan tab" rather than "No route".
    if has "$(ui empty_plan)"; then return 0; fi
    p=$(node "$(ui undo)") || return 0
    read -r _ _ x1 y1 x2 y2 <<< "$p"
    tap_xy "$(( x1 + (x2 - x1) * 5 / 10 ))" "$(( y1 + (y2 - y1) * 35 / 100 ))"
    sleep 3
  done
  say "the plan would not clear"
}

open_demo_route_in_planner() {
  go_tab "$(ui tab_library)"
  tap "$(ui lib_routes)" 2> /dev/null || true
  sleep 2
  wait_for 'Funchal coast and Monte route' 30
  tap 'Funchal coast and Monte route'
  wait_for "$(ui open_in_planner)" 30
  tap "$(ui open_in_planner)"
  wait_for "$(ui DISTANCE)" 90 "the route did not open in the planner"
  sleep 6
  # The camera fit does not know about the sheet, so the loop sits low: lift it.
  A shell input swipe 540 1150 540 870 500
  sleep 4
}

cap_planner() { open_demo_route_in_planner; shot "$1" planner; }

cap_loop() {
  local look=$1 p
  clear_plan
  # Put the rider back on the Funchal seafront and frame the map so the loop
  # the search draws lands in the strip above the sheet.
  A emu geo fix -16.9075 32.6465 > /dev/null
  sleep 2
  tap "$(ui locate)"
  sleep 5
  # Locating jumps to street level; back out until a loop of this size fits.
  for _ in 1 2 3 4; do
    tap "$(ui zoom_out)"
    sleep 2
  done
  A shell input swipe 540 1200 540 700 500
  sleep 3
  p=$(node "$(ui undo)")
  # `set --` below overwrites $1, so the folder name is held in $look.
  set -- $p
  tap_xy "$(( $3 + ($5 - $3) * 9 / 10 ))" "$(( $4 + ($6 - $4) * 35 / 100 ))"
  wait_for "$(ui loop_make)" 30 "the Smart Loop sheet did not open"
  sleep 2
  tap "$(ui loop_make)" 1
  # On-device loop search over the Madeira tile; around half a minute.
  if wait_for "$(ui loop_result)" 240; then
    sleep 3
    shot "$look" loop
  else
    say "the loop search did not finish; capturing the request sheet instead"
    shot "$look" loop
  fi
  tap "$(ui loop_done)" 2> /dev/null || tap "$(ui dismiss)" 2> /dev/null || true
  sleep 3
}

cap_search() {
  clear_plan
  tap "$(ui search_hint)"
  sleep 4
  keyboard_up || { sleep 3; tap "$(ui search_hint)"; sleep 3; }
  type_text "Funchal"
  wait_for "$(ui hit_funchal)" 40 "the offline gazetteer returned nothing"
  sleep 3
  shot "$1" search
  hide_keyboard
  tap "$(ui search_clear)" 2> /dev/null || true
  sleep 2
}

start_ride() {  # start_ride <dropdown item: "No route" or a saved route>
  go_tab "$(ui tab_record)"
  # Always say what to follow: the dropdown keeps whatever the last ride used,
  # and its null item silently means "the route on the Plan tab".
  tap "$(ui follow_route)"
  if ! wait_for "^$1\$" 20; then
    # "No route" is only offered while the Plan tab holds no route; if one
    # crept back in, close the menu, clear it and ask again.
    tap "$(ui dismiss)" || true
    sleep 2
    clear_plan
    go_tab "$(ui tab_record)"
    tap "$(ui follow_route)"
    wait_for "^$1\$" 20 "the Follow a route menu has no \"$1\""
  fi
  tap "^$1\$"
  sleep 3
  tap "$(ui start_ride)"
  sleep 5
  # The one-time battery dialog, and the location rationale before it.
  if has "$(ui not_now)"; then
    tap "$(ui not_now)"
    sleep 4
  fi
  if has "$(ui rationale_allow)" && ! has "$(ui RECORDING)"; then
    tap "$(ui rationale_allow)"
    sleep 4
  fi
  # The panel says AUTO-PAUSED until the first fix moves, so the stop button
  # is what says the ride is running.
  wait_for "$(ui finish)" 60 "the ride did not start"
}

stop_ride() {
  tap "$(ui finish)" 2> /dev/null || true
  sleep 12
  if has "$(ui menu)"; then  # the finished ride's detail screen
    tap "$(ui menu)"
    sleep 3
    tap "$(ui delete)"
    sleep 5
    dismiss_snackbar
  fi
}

ride_along() {  # ride_along <path file> <km/h>
  python3 tool/emu_ride.py --path "$1" "$2" "$SERIAL" > "$WORK/emu_ride.log" 2>&1 &
  RIDE_PID=$!
}

stop_riding() {
  [ -n "${RIDE_PID:-}" ] || return 0
  kill "$RIDE_PID" 2> /dev/null || true
  wait "$RIDE_PID" 2> /dev/null || true
  RIDE_PID=
}

cap_navigation() {
  A emu geo fix "$(head -2 "$WORK/monte.path" | tail -1 | cut -d, -f2)" \
    "$(head -2 "$WORK/monte.path" | tail -1 | cut -d, -f1)" > /dev/null
  sleep 3
  start_ride "Funchal to Monte"
  ride_along "$WORK/monte.path" 18
  # Ride for a while first, so the panel shows a believable distance rather
  # than the first hundred metres.
  sleep 90
  # Then wait for a turn that is close enough to read as guidance but not so
  # close that the banner has already switched to the one after it.
  local i turn far
  for ((i = 0; i < 60; i++)); do
    dump || true
    turn=$(python3 "$HERE/ui.py" grep "$WORK/ui.xml" "$(ui turn)" || true)
    far=$(python3 "$HERE/ui.py" grep "$WORK/ui.xml" "$(ui metres)" || true)
    if [ -n "$turn" ] && [ -n "$far" ] && [ "${far% m}" -ge 80 ] && [ "${far% m}" -le 350 ]; then
      break
    fi
    sleep 3
  done
  [ -n "$turn" ] || say "no turn instruction appeared; capturing whatever the banner shows"
  wait_for "$(ui RECORDING)" 40 || say "the recorder is not in the RECORDING state"
  shot "$1" navigation
  stop_riding
  stop_ride
}

cap_recording() {
  # An empty plan, so "No route" really is no route and no turn banner shows.
  clear_plan
  A emu geo fix "$(head -2 "$WORK/seafront.path" | tail -1 | cut -d, -f2)" \
    "$(head -2 "$WORK/seafront.path" | tail -1 | cut -d, -f1)" > /dev/null
  sleep 3
  start_ride "$(ui no_route)"
  ride_along "$WORK/seafront.path" 22
  sleep 100
  wait_for "$(ui RECORDING)" 40 || say "the recorder is not in the RECORDING state"
  shot "$1" recording
  stop_riding
  stop_ride
}

cap_ride() {
  go_tab "$(ui tab_library)"
  tap "$(ui lib_rides)"
  sleep 3
  wait_for 'Funchal coast and Monte loop' 30
  tap 'Funchal coast and Monte loop'
  wait_for "$(ui SLOW)" 60 "the ride detail did not open"
  sleep 6
  # Down far enough that the map hero is out of the way and both charts fit
  # above the floating tab bar. Both swipes start inside the stats grid: a
  # drag that lands on a chart leaves its readout ("10.7 km · 684 m") on
  # screen, which reads as a stuck tooltip in a screenshot.
  A shell input swipe 540 1500 540 1100 600
  sleep 2
  A shell input swipe 540 1100 540 850 600
  sleep 4
  shot "$1" ride
  tap "$(ui back)" 2> /dev/null || true
  sleep 3
}

cap_library() {
  go_tab "$(ui tab_library)"
  tap "$(ui lib_routes)"
  sleep 4
  shot "$1" library
}

cap_offline() {
  go_tab "$(ui tab_plan)"
  tap "$(ui offline_entry)"
  wait_for "$(ui routing_data)" 40 "the offline screen did not open"
  sleep 5
  shot "$1" offline
  tap "$(ui back)" 2> /dev/null || true
  sleep 3
}

cap_settings() {
  go_tab "$(ui tab_settings)"
  sleep 4
  shot "$1" settings
}

capture_look() {  # capture_look <mode-accent>
  local look=$1 mode=${1%%-*} accent=${1#*-}
  say "appearance: $mode + $accent"
  restart_with "$mode" "$accent"
  local screen
  for screen in "${SCREENS[@]}"; do
    say "  $screen"
    case "$screen" in
      planner) cap_planner "$look" ;;
      loop) cap_loop "$look" ;;
      search) cap_search "$look" ;;
      navigation) cap_navigation "$look" ;;
      recording) cap_recording "$look" ;;
      ride) cap_ride "$look" ;;
      library) cap_library "$look" ;;
      offline) cap_offline "$look" ;;
      settings) cap_settings "$look" ;;
      *) die "unknown screen $screen" ;;
    esac
  done
}

write_manifest() {
  say "writing $OUT/manifest.json"
  VELORKI_SHOT_RES="$RES" VELORKI_SHOT_DENSITY="$DENSITY" \
    VELORKI_SHOT_LOOKS="${ALL_LOOKS[*]}" VELORKI_SHOT_SCREENS="${ALL_SCREENS[*]}" \
    python3 - "$OUT" << 'PY'
import datetime, json, os, sys

out = sys.argv[1]
looks = os.environ["VELORKI_SHOT_LOOKS"].split()
screens = os.environ["VELORKI_SHOT_SCREENS"].split()
width, height = os.environ["VELORKI_SHOT_RES"].split("x")
# English, in every language: these describe the shot, not what the app says
# in it. The site's own alt texts are translated in web/messages/*.json.
titles = {
    "planner": "Planning the Funchal coast and Monte loop",
    "loop": "Smart Loop, a ride of about the length you asked for",
    "search": "Searching the offline gazetteer",
    "navigation": "Turn-by-turn guidance while recording",
    "recording": "A ride being recorded",
    "ride": "A finished ride, with its charts and splits",
    "library": "Saved routes and rides",
    "offline": "Offline map and routing data",
    "settings": "Settings, with the appearance block",
}
# Every language with a set on disk, not only the one this run took: a German
# run must leave the English sets in the manifest. English first, the rest
# alphabetically.
languages = sorted(
    name
    for name in os.listdir(out)
    if any(os.path.isdir(os.path.join(out, name, look)) for look in looks)
)
languages.sort(key=lambda tag: (tag != "en", tag))

sets = []
for language in languages:
    for look in looks:
        mode, accent = look.split("-", 1)
        shots = []
        for screen in screens:
            relative = f"{language}/{look}/{screen}.png"
            path = os.path.join(out, relative)
            if not os.path.exists(path):
                continue
            shots.append({
                "screen": screen,
                "title": titles[screen],
                "file": relative,
                "bytes": os.path.getsize(path),
            })
        if shots:
            sets.append({
                "language": language,
                "mode": mode,
                "accent": accent,
                "screenshots": shots,
            })

manifest = {
    "generatedAt": datetime.datetime.now(datetime.timezone.utc)
        .strftime("%Y-%m-%dT%H:%M:%SZ"),
    "device": {
        "name": "Android emulator, Pixel-class phone",
        "platform": "android",
        "width": int(width),
        "height": int(height),
        "density": int(os.environ["VELORKI_SHOT_DENSITY"]),
        "statusBar": "SystemUI demo mode: 09:41, full battery, Wi-Fi, no notifications",
    },
    "region": {
        "name": "Funchal, Madeira",
        "routingTile": "W20_N30",
        "demoRoute": "Funchal coast and Monte route",
        "demoRide": "Funchal coast and Monte loop",
        "navigationRoute": "Funchal to Monte",
    },
    "languages": languages,
    "sets": sets,
}
with open(os.path.join(out, "manifest.json"), "w") as fh:
    json.dump(manifest, fh, indent=2)
    fh.write("\n")
PY
}

# --------------------------------------------------------------------- main

require_device
start_mirror
if [ "$DO_BUILD" = 1 ]; then build_and_install; fi
demo_mode
# Before the seeding, which taps the same translated labels the captures do.
set_language "$LANG_TAG"
if [ "$DO_SEED" = 1 ]; then
  seed
else
  launch
  head -14 "$HERE/demo-loop.path" > "$WORK/seafront.path"
  db "select 1" > /dev/null || die "the app database could not be read"
  python3 "$HERE/unpack_route.py" "$WORK/velorki.sqlite" "Funchal to Monte" > "$WORK/monte.path"
fi

mkdir -p "$OUT"
for look in "${LOOKS[@]}"; do
  capture_look "$look"
done

write_manifest
# Hand the app back on System, whatever this run was in.
set_language en
demo_mode_off
say "done: $OUT/$LANG_TAG"
